// bugs.jsx — daily C bug challenges, progressive difficulty
const BUGS = [
  {
    id: 1,
    day: 'Jour 1',
    difficulty: 'Facile',
    streakLevel: 1,
    title: 'La boucle qui dépasse',
    desc: "Cette fonction calcule la somme d'un tableau, mais lit une case en trop.",
    code: [
      'int sum_array(int arr[], int n) {',
      '  int sum = 0;',
      '  for (int i = 0; i <= n; i++) {',
      '    sum += arr[i];',
      '  }',
      '  return sum;',
      '}',
    ],
    bugLine: 2,
    answer: 'for (int i = 0; i < n; i++) {',
    accept: [
      /for\s*\(\s*int\s+i\s*=\s*0\s*;\s*i\s*<\s*n\s*;\s*i\s*\+\+\s*\)\s*\{?/,
    ],
    hint: "Que se passe-t-il à la dernière itération quand i == n ?",
    explanation: "arr[n] est hors limites — un tableau indexé de 0 à n-1 a n éléments. Il faut s'arrêter avant n.",
    xp: 10,
  },
  {
    id: 2,
    day: 'Jour 2',
    difficulty: 'Facile',
    streakLevel: 2,
    title: '= ou == ?',
    desc: "Cette condition ne fait jamais ce qu'on attend. Pourquoi ?",
    code: [
      'int is_winner(int score) {',
      '  if (score = 100) {',
      '    return 1;',
      '  }',
      '  return 0;',
      '}',
    ],
    bugLine: 1,
    answer: 'if (score == 100) {',
    accept: [
      /if\s*\(\s*score\s*==\s*100\s*\)\s*\{?/,
    ],
    hint: "= est une affectation, pas une comparaison.",
    explanation: "score = 100 affecte 100 à score puis évalue à 100 (truthy) — la fonction renvoie toujours 1.",
    xp: 10,
  },
  {
    id: 3,
    day: 'Jour 3',
    difficulty: 'Moyen',
    streakLevel: 3,
    title: 'Le pointeur fantôme',
    desc: "Ce code copie une chaîne mais plante à l'exécution.",
    code: [
      '#include <string.h>',
      '',
      'char *greet(void) {',
      '  char *buf;',
      '  strcpy(buf, "Bonjour");',
      '  return buf;',
      '}',
    ],
    bugLine: 4,
    answer: '  char *buf = malloc(8);',
    accept: [
      /char\s*\*\s*buf\s*=\s*malloc\s*\(\s*\d+\s*\)\s*;?/,
      /char\s+buf\s*\[\s*\d+\s*\]\s*;?/,
    ],
    hint: "Tu écris dans un pointeur qui ne pointe nulle part.",
    explanation: "buf n'a pas de mémoire allouée — strcpy écrit dans une adresse non initialisée. Alloue avec malloc ou utilise un buffer statique.",
    xp: 20,
  },
  {
    id: 4,
    day: 'Jour 4',
    difficulty: 'Moyen',
    streakLevel: 4,
    title: 'La fuite silencieuse',
    desc: 'Cette fonction alloue mais oublie de rendre la mémoire.',
    code: [
      'void process(int n) {',
      '  int *arr = malloc(n * sizeof(int));',
      '  for (int i = 0; i < n; i++) {',
      '    arr[i] = i * i;',
      '  }',
      '  print_sum(arr, n);',
      '}',
    ],
    bugLine: 5,
    answer: '  print_sum(arr, n);\n  free(arr);',
    accept: [
      /free\s*\(\s*arr\s*\)\s*;/,
    ],
    hint: "Chaque malloc doit avoir son free.",
    explanation: "Sans free(arr), la mémoire reste allouée jusqu'à la fin du programme — fuite mémoire.",
    xp: 20,
  },
  {
    id: 5,
    day: 'Jour 5',
    difficulty: 'Moyen',
    streakLevel: 5,
    title: 'Division dangereuse',
    desc: "La moyenne tombe parfois sur une division par zéro.",
    code: [
      'float average(int *arr, int n) {',
      '  int sum = 0;',
      '  for (int i = 0; i < n; i++)',
      '    sum += arr[i];',
      '  return sum / n;',
      '}',
    ],
    bugLine: 4,
    answer: '  return n > 0 ? (float)sum / n : 0.0f;',
    accept: [
      /n\s*[>!]\s*=?\s*0/,
      /if\s*\(\s*n\s*==\s*0\s*\)/,
    ],
    hint: "Que vaut sum / n quand n == 0 ?",
    explanation: "Diviser par zéro plante (ou retourne NaN/inf). Garde-fou nécessaire.",
    xp: 25,
  },
];

window.BUGS = BUGS;
